# Generated by Django 4.1 on 2024-10-17 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="job",
            name="Vacancy",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="job",
            name="experiences",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name="job",
            name="catgory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="job.category",
            ),
            preserve_default=False,
        ),
    ]
