# Generated by Django 5.1.2 on 2024-10-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_category_alter_job_vacancy_alter_job_experiences_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="Image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
